### PR TITLE
So this does something...

### PR DESCRIPTION
**Pull request by amouat**
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]

**Comment by jdolitsky** [comment]
Do we want this still?

**Comment by amouat** [comment]
Definitely want it, I think that was me checking in WIP before paternity leave for whoever took over the task

**Comment by jdolitsky** [comment]
well looks like it builds ok at least :) wanna rebase?

**Comment by amouat** [comment]
I've merged it, but maybe I shouldn't have 😂 

The thing is for wolfi we'll have to use the generic tarball rather than the apk which has a musl build.

**Pull request merged**
